# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Covid19Doctor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Covid19Doctor
  
  # reactive
  pod 'RxSwift'
  pod 'RxRelay'
  pod 'RxCocoa'
  pod 'RxSwiftExt'
  pod 'RxGesture'
  pod 'RxAppState'
  
  # database
  pod 'RealmSwift', '4.4.0'
  
  # UI
  pod 'PMSuperButton'
  pod 'KWVerificationCodeView'
  pod 'PhoneNumberKit'
  pod 'Toast-Swift'
  pod 'FittableFontLabel'
  pod 'DropDown'
  
  # crash reporting
  pod 'Sentry', '4.5.0'

end
