# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Covid19Doctor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Covid19Doctor
  pod 'RxSwift'
  pod 'RxRelay'
  pod 'RxCocoa'
  pod 'RxSwiftExt'
  pod 'RxGesture'
  pod 'RxAppState'
  pod 'PMSuperButton'
  pod 'KWVerificationCodeView'
  pod 'PhoneNumberKit'
  pod 'Toast-Swift'

end
